In [1]:
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import BernoulliNB
from sklearn import datasets
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
%matplotlib inline

In [2]:
iris=datasets.load_iris()

In [ ]:
iris

{'DESCR': 'Iris Plants Database\n====================\n\nNotes\n-----\nData Set Characteristics:\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20  0.76     0.9565  (high!)\n    ============== ==== ==== ======= ===== ==

In [4]:
X=iris.data
y=iris.target

In [5]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3)

## Gaussian Naive Bayes

### 主要用於連續變數，比方說特徵長度為幾公分、重量為幾公斤等等。

$$ P(X_j|Y_i)=\frac{1}{\sqrt{2\pi\sigma_{Y_i}^2}} exp(-\frac{(X_j-\mu_{Y_i})^2}{2\sigma_{Y_i}^{2}})$$

In [6]:
modelg=GaussianNB()
modelg.fit(X_train,y_train)
modelg.predict(X_test)

array([0, 1, 1, 0, 1, 0, 0, 2, 1, 1, 1, 0, 0, 2, 1, 2, 1, 0, 0, 2, 2, 2,
       1, 0, 2, 0, 0, 2, 1, 1, 0, 2, 0, 0, 0, 0, 0, 1, 2, 1, 2, 2, 0, 0,
       0])

In [7]:
modelg.predict_proba(X_test)

array([[1.00000000e+000, 2.03950657e-013, 3.52586548e-025],
       [1.65606269e-085, 9.95420614e-001, 4.57938625e-003],
       [1.22634479e-071, 9.99854617e-001, 1.45382838e-004],
       [1.00000000e+000, 1.26438337e-015, 3.07949246e-028],
       [3.20136071e-107, 8.72637705e-001, 1.27362295e-001],
       [1.00000000e+000, 3.81762325e-016, 2.92323404e-028],
       [1.00000000e+000, 1.34197107e-014, 4.28606770e-027],
       [7.35739425e-149, 3.04629379e-002, 9.69537062e-001],
       [2.43530339e-119, 9.81605343e-001, 1.83946566e-002],
       [2.36722840e-107, 7.04869088e-001, 2.95130912e-001],
       [1.14927225e-068, 9.99990403e-001, 9.59699992e-006],
       [1.00000000e+000, 7.43810213e-011, 1.08750231e-021],
       [1.00000000e+000, 1.13964018e-014, 6.48142568e-027],
       [4.29768862e-129, 1.78078310e-001, 8.21921690e-001],
       [7.67898686e-091, 9.97357303e-001, 2.64269739e-003],
       [8.01568015e-258, 1.10351239e-008, 9.99999989e-001],
       [6.35168280e-075, 9.99675285e-001

In [8]:
print('Training Set Score:',modelg.score(X_train,y_train))
print('Test Set Score:',modelg.score(X_test,y_test))

Training Set Score: 0.9428571428571428
Test Set Score: 0.9777777777777777


## Multinomial Naive Bayes

### 主要用在離散變數，比方說次數、類別等等。

 $$ P(Y_i)=\frac{N_{Y_i}+\alpha}{N+K_\alpha} $$
 $$ $$
 $$P(X_j|Y_i)=\frac{N_{Y_i,x_j}+\alpha}{N_{Y_i}+n\alpha} $$


In [9]:
modelm=MultinomialNB()
modelm.fit(X_train,y_train)
modelm.predict(X_test)

array([0, 1, 1, 0, 1, 0, 0, 2, 2, 1, 1, 0, 0, 2, 1, 2, 1, 0, 0, 2, 2, 2,
       1, 0, 2, 0, 0, 2, 1, 1, 0, 2, 0, 0, 0, 0, 0, 1, 2, 1, 2, 1, 0, 0,
       0])

In [ ]:
modelm.predict_proba(X_test)

array([[0.00774907, 0.41245383, 0.5797971 ],
       [0.71248848, 0.17410151, 0.11341001],
       [0.71326005, 0.17434433, 0.11239562],
       [0.01371604, 0.47131675, 0.51496722],
       [0.04056004, 0.45742259, 0.50201737],
       [0.05581974, 0.46417425, 0.48000601],
       [0.74893148, 0.15376235, 0.09730617],
       [0.01942044, 0.44712168, 0.53345788],
       [0.00768361, 0.42796666, 0.56434973],
       [0.71326005, 0.17434433, 0.11239562],
       [0.82811946, 0.10980533, 0.06207521],
       [0.06888248, 0.47251483, 0.45860269],
       [0.04312441, 0.47500947, 0.48186612],
       [0.07617958, 0.46668905, 0.45713136],
       [0.09596198, 0.45792753, 0.44611049],
       [0.08231808, 0.46318907, 0.45449285],
       [0.72800333, 0.16648403, 0.10551264],
       [0.73116422, 0.16434723, 0.10448855],
       [0.01357927, 0.44197285, 0.54444788],
       [0.73189277, 0.16456222, 0.10354501],
       [0.06246499, 0.47448864, 0.46304638],
       [0.04303825, 0.47726627, 0.47969548],
       [0.

In [10]:
print('Training Set Score:',modelm.score(X_train,y_train))
print('Test Set Score:',modelm.score(X_test,y_test))

Training Set Score: 0.9523809523809523
Test Set Score: 0.9777777777777777


## Bernoulli Naive Bayes

### 用在二元的特徵，比方說特徵是否出現、特徵大小、特徵長短等等這種二元的分類。

$$ P(X_j|Y_i)=P_{Y_i}^{X_j}(1-P_{Y_i})^{X_j} $$

In [11]:
modelb = BernoulliNB()
modelb.fit(X_train,y_train)
modelb.predict(X_test)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1])

In [12]:
modelb = BernoulliNB(binarize=1)
modelb.fit(X_train,y_train)
modelb.predict(X_test)

array([0, 2, 2, 0, 2, 0, 0, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 0, 0, 2, 2, 2,
       2, 0, 2, 0, 0, 2, 2, 2, 0, 2, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 0, 0,
       0])

In [13]:
modelb.score(X_test,y_test)

0.7333333333333333

In [14]:
X=pd.DataFrame(X)
X.describe()

0           1           2           3
count  150.000000  150.000000  150.000000  150.000000
mean     5.843333    3.057333    3.758000    1.199333
std      0.828066    0.435866    1.765298    0.762238
min      4.300000    2.000000    1.000000    0.100000
25%      5.100000    2.800000    1.600000    0.300000
50%      5.800000    3.000000    4.350000    1.300000
75%      6.400000    3.300000    5.100000    1.800000
max      7.900000    4.400000    6.900000    2.500000

In [16]:
modelb = BernoulliNB()
modelb.fit(X_train,y_train)
modelb.predict(X_test)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1])

In [17]:
modelb.predict_proba(X_test)

array([[0.28075547, 0.36489017, 0.35435436],
       [0.28075547, 0.36489017, 0.35435436],
       [0.28075547, 0.36489017, 0.35435436],
       [0.28075547, 0.36489017, 0.35435436],
       [0.28075547, 0.36489017, 0.35435436],
       [0.28075547, 0.36489017, 0.35435436],
       [0.28075547, 0.36489017, 0.35435436],
       [0.28075547, 0.36489017, 0.35435436],
       [0.28075547, 0.36489017, 0.35435436],
       [0.28075547, 0.36489017, 0.35435436],
       [0.28075547, 0.36489017, 0.35435436],
       [0.28075547, 0.36489017, 0.35435436],
       [0.28075547, 0.36489017, 0.35435436],
       [0.28075547, 0.36489017, 0.35435436],
       [0.28075547, 0.36489017, 0.35435436],
       [0.28075547, 0.36489017, 0.35435436],
       [0.28075547, 0.36489017, 0.35435436],
       [0.28075547, 0.36489017, 0.35435436],
       [0.28075547, 0.36489017, 0.35435436],
       [0.28075547, 0.36489017, 0.35435436],
       [0.28075547, 0.36489017, 0.35435436],
       [0.28075547, 0.36489017, 0.35435436],
       [0.

In [18]:
print('Training Set Score:',modelb.score(X_train,y_train))
print('Test Set Score:',modelb.score(X_test,y_test))

Training Set Score: 0.3619047619047619
Test Set Score: 0.26666666666666666
